apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: "{{.Name}}"
  namespace: "{{.Namespace}}"
  labels:
    hvperf/run: "{{.RunID}}"
  annotations:
    harvesterhci.io/volumeClaimTemplates: |
      [{"metadata":{"name":"{{.Name}}-disk","labels":{"hvperf/run":"{{.RunID}}"},"annotations":{"harvesterhci.io/imageId":"{{.ImageID}}"}},"spec":{"accessModes":["ReadWriteMany"],"storageClassName":"{{.StorageClass}}","volumeMode":"Block","resources":{"requests":{"storage":"{{.DiskSize}}"}}}}]
spec:
  runStrategy: RerunOnFailure
  template:
    spec:
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        resources:
          requests:
            memory: "{{.Memory}}"
            cpu: "{{.CPU}}"
          limits:
            memory: "{{.Memory}}"
            cpu: "{{.CPU}}"
        devices:
          disks:
          - name: rootdisk
            disk:
              bus: virtio
      volumes:
      - name: rootdisk
        persistentVolumeClaim:
          claimName: "{{.Name}}-disk"
