apiVersion: harvesterhci.io/v1beta1
kind: VirtualMachineImage
metadata:
  name: "{{.Name}}"
  namespace: "{{.Namespace}}"
  labels:
    hvperf/run: "{{.RunID}}"
spec:
  displayName: "{{.Name}}"
  sourceType: download
  url: "{{.URL}}"
