name: Refactor
description: Refactoring of benchmark code or framework
title: "[REFACTOR] "
type: "Task"
labels: ["kind/refactor"]
assignees:
-
body:
- type: textarea
  attributes:
    label: What to refactor and why?
    description: Describe the current issue and the intended improvement.
  validations:
    required: true

- type: textarea
  attributes:
    label: Additional context
  validations:
    required: false
